# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='whitenoise.django.GzipManifestStaticFilesStoragecases', verbose_name='Imagem'),
        ),
    ]
