# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20180215_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cases_imagem', verbose_name='Imagem'),
        ),
    ]
