# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20180215_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='cases',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cases', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='products',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cases.Cases', verbose_name='Case'),
        ),
    ]
