# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20180301_1843'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='case',
            managers=[
            ],
        ),
    ]
