# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 19:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20180301_1936'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='case',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
